POST {{base_url}}/authenticate
Content-Type: application/json
Accept: application/json

{
    "email": "test@example.com",
    "password": "password"
}

> {% client.global.set("auth_token", response.body.token); %}

###

GET {{base_url}}/user
Authorization: Bearer {{auth_token}}

###

GET {{base_url}}/customers
Authorization: Bearer {{auth_token}}

> {% client.global.set("customer_id", response.body.data[0].id); %}

###

GET {{base_url}}/customers/{{customer_id}}
Authorization: Bearer {{auth_token}}

###

POST {{base_url}}/customers
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
    "first_name": "John",
    "last_name": "Doe",
    "document": "175.221.910-41",
    "birthdate": "2001-02-21",
    "gender": "M",
    "address": {
        "street": "Rua dos Bobos",
        "number": "0",
        "complement": "Apto 123",
        "district": "Centro",
        "city": "São Paulo",
        "state": "SP",
        "country": "BR",
        "zip_code": "12345-678"
    }
}

###

PUT {{base_url}}/customers/{{customer_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
    "first_name": "João",
    "last_name": "Dunha",
    "document": "52181024073",
    "birthdate": "2001-02-21",
    "gender": "F",
    "address": {
        "street": "Av das Antas",
        "number": "0",
        "complement": "Apto 456",
        "district": "Perdizes",
        "city": "São Paulo",
        "state": "SP",
        "country": "BR",
        "zip_code": "12345678"
    }
}

###

DELETE {{base_url}}/customers/{{customer_id}}
Accept: application/json
Authorization: Bearer {{auth_token}}
